name: Dockerized Node App Deployment

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub (Optional)
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker image
      run: |
        docker build -t dockerized-node-app .
        docker save dockerized-node-app | gzip > dockerized-node-app.tar.gz

    - name: Setup SSH Connection
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Copy Docker image to Server
      run: |
        scp -o StrictHostKeyChecking=no dockerized-node-app.tar.gz root@${{ secrets.SERVER_IP }}:/root/

    - name: Deploy on Server
      run: |
        ssh -o StrictHostKeyChecking=no root@${{ secrets.SERVER_IP }} "
          docker load < dockerized-node-app.tar.gz &&
          docker stop node-app || true &&
          docker rm node-app || true &&
          docker run -d -p 80:3000 --name node-app --env-file /root/.env dockerized-node-app
        "
